### ISSUE TITLE
openstack action is not able to establish connection behind the proxy settings

### ISSUE THREAD

**Issue by QualoZe0t** [StackStorm-Exchange/stackstorm-openstack#10]
I am trying to execute openstack action behind the proxy settings. I  am able to install any pack and execute them except openstack. Connection to keystone api is not able to establish neither when I will specify it in rc.file (like export ..) or /etc/env file or /opt/stackstorm/packs/packs/actions/setup_virtualenv.yaml, /opt/stackstorm/packs/packs/actions/download.yaml .. When I will execute wget for keystone api this is working properly 
```wget http://198.18.148.124:5000/v2.0
--2017-07-31 10:03:15--  http://198.18.148.124:5000/v2.0
Connecting to 10.10.128.200:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 340 [application/json]
Saving to: ‘v2.0.2’

v2.0.2                                             100%[================================================================================================================>]     340  --.-KB/s    in 0s      

2017-07-31 10:03:15 (36.4 MB/s) - ‘v2.0.2’ saved [340/340]```
**

but when i will try to execute st2 run openstack.user.show user=admin
```..
id: 597f015c7d05072e46db1fe8
status: failed
parameters: 
  user: admin
result: 
  exit_code: 1
  result: None
  stderr: 'st2.actions.python.WrapperAction: DEBUG    Generated command "openstack user show -f json admin"

    Failed to discover available identity versions when contacting http://198.18.148.124:5000/v2.0. Attempting to parse version from URL.

    Unable to establish connection to http://198.18.148.124:5000/v2.0/tokens: HTTPConnectionPool(host=''198.18.148.124'', port=5000): Max retries exceeded with url: /v2.0/tokens (Caused by NewConnectionError(''<requests.packages.urllib3.connection.HTTPConnection object at 0x7fba0de122d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'',))

    '
  stdout: ''
ubuntu@ansible-node:~$ 
```
openstack config.yaml file was configured and set up using password..

can you try to check from your set up if this is typical behaviour  or there is some bug ?

**Comment by Kami** [comment]
Did you try setting environment variable on per-action invocation basis as mentioned on Slack?

```bash
st2 --debug run openstack.foo env="http_proxy=foo,https_proxy=bar" more parameters...
```

Also, for future reference https://github.com/StackStorm/st2/pull/3556#issuecomment-319023889

**Comment by QualoZe0t** [comment]
i have tried to use your idea and i've got success . Let me do more tests
```buntu@ansible-node:~$ st2 run openstack.user.show user=admin env="http_proxy="http://10.10.128.200:3128",https_proxy="http://10.10.128.200:3128""
..
id: 597f05017d05072e46db1fee
status: succeeded
parameters: 
  env:
    http_proxy: http://10.10.128.200:3128
    https_proxy: http://10.10.128.200:3128
  user: admin
result: 
  exit_code: 0
  result:
    enabled: true
    id: f6f2f9f25e3241978b2f079695dba029
    name: admin
    project_id: 01aa33baf27049e196f053504a5966ad
  stderr: 'st2.actions.python.WrapperAction: DEBUG    Generated command "openstack user show -f json admin"

    '
  stdout: ''
ubuntu@ansible-node:~$ ```

**Comment by QualoZe0t** [comment]
based on your idea now openstack is reachable but i am not sure if using extra arg like env is good solution as I have already specify proxy settings in /etc/env .. it will be very good if any action will check if proxy is not already configured and use it automatically.

**Comment by arm4b** [comment]
Take a look at https://docs.stackstorm.com/latest/packs.html#installing-packs-from-behind-a-proxy which describes how to configure proxy settings for st2 since `v2.3.2` version.

**Comment by QualoZe0t** [comment]
great this fixed my problem with openstack 
root@ansible-node:~# st2 run openstack.user.show user=admin
```
..
id: 597f23e47d0507466a805f11
status: succeeded
parameters: 
  user: admin
result: 
  exit_code: 0
  result:
    enabled: true
    id: f6f2f9f25e3241978b2f079695dba029
    name: admin
    project_id: 01aa33baf27049e196f053504a5966ad
  stderr: 'st2.actions.python.WrapperAction: DEBUG    Generated command "openstack user show -f json admin"

    '
  stdout: ''
root@ansible-node:~# 
```

**Comment by Kami** [comment]
So to confirm, upgrading to v2.3.2 resolved the issue?

**Comment by QualoZe0t** [comment]
well i have upgraded to 2.3.2 + created st2api and st2action runner and put inside proxy config. Now it is working properly. But just update to 2.3.2 didnt fix the issue

**Comment by Kami** [comment]
Thanks for confirming, will close this issue.

@lakshmi-kannan If not already, can we please also document how to set environment variables (notably for proxy) for various st2 services (modifying service manager file)?

**Comment by arm4b** [comment]
@Kami The doc @QualoZe0t was following https://docs.stackstorm.com/latest/packs.html#installing-packs-from-behind-a-proxy since `v2.3.2` already clarifies that.

**Comment by Kami** [comment]
@armab Great, so we are all good then :)
