### ISSUE TITLE
Course of action for v3 Identity API upgrade

### ISSUE THREAD

**Issue by vdombrovski** [StackStorm-Exchange/stackstorm-openstack#11]
I am currently working on enhancing this pack with the OpenStack identity v3 API actions. (groups/domains already available at my fork).

Apart from introducing new features (such as groups and domains), the v3 API also introduces new parameters to existing actions (most notably by adding domain isolation pretty much everywhere).

Such an upgrade would however break the currently existing v2 API implementation. Thus, before submitting a pull request, I would love to have some advice on which course of action would be better:

(a) Leave the existing v2 actions, and make separate v3 versions of them (e.g. project.create.v3)
(b) Fully upgrade to the v3 API, thus removing the existing compatibility with the deprecated v2 API.
(c) Detect which API version is configured, and throw an error when the user tries to pass a v3 parameter while using the v2 API and vice versa (if applicable)
(d) There is no desire at all to upgrade to v3, in which case I won't bother making the PR.

**Comment by LindsayHill** [comment]
Thanks for looking into this @vdombrovski 

How widespread is the use of the OpenStack identity v3 API? If it is now available to most users, then I would be in favour of either (b) or (c).

I am not in favour of (a). Users that need to use the existing implementation can install a specific version of this pack (e.g. with `st2 pack install openstack=0.x.x`). The main thing for us is that we increment the pack version when making a change, and document it for users.

**Comment by ntk148v** [comment]
This issue might relate to PR #25

**Comment by bigmstone** [comment]
I'm going to close since this has been open so long w/o response. If it needs to be re-opened feel free.
