### ISSUE TITLE
OpenStack pack doesn't install on python 2

### ISSUE THREAD

**Issue by amanda11** [StackStorm-Exchange/stackstorm-openstack#33]
Due to dependencies that are python3 only, the openstack pack currently will not install on python 2 system.

It can be installed and run successfully on ST2 systems that use python 2 with the  --python3 pack, as long as the appropriate ST2 parameters to specify the python3 binary and library prefix are specified.

If the requirements is changed to pyrsistent < 0.17 then it installs, but errors were then seen running server list for example as the openstack library was referring to modules that didn't exist.

**Comment by amanda11** [comment]
Currently looking to see if there is a problem with latest openstackclient library to see if there is a version that will work on a py2 system, to resolve error:

```
  File \"/opt/stackstorm/virtualenvs/openstack/lib/python2.7/site-packages/openstack/proxy.py\", line 24, in <module>
    from openstack import resource
  File \"/opt/stackstorm/virtualenvs/openstack/lib/python2.7/site-packages/openstack/resource.py\", line 49, in <module>
    from openstack import utils
  File \"/opt/stackstorm/virtualenvs/openstack/lib/python2.7/site-packages/openstack/utils.py\", line 13, in <module>
    import queue
  ImportError: No module named queue
```

**Comment by amanda11** [comment]
Seems above is a well known issue with python2, but with many suggestions of fixing it manually, eg. https://kyle.pericak.com/openstack-fix-cli.html and https://ask.openstack.org/en/question/128326/python-openstackclient-not-working-importerror-no-module-named-queue/

**Comment by amanda11** [comment]
Original plan was to fix latest version so it installs on py2, but then make version 1.0.0 py3 only (https://github.com/StackStorm-Exchange/stackstorm-openstack/pull/31). However that was when thought was just a pyristent version change needed, rather than it appears that to get pack to work on py2 then need to make  pyristent < 0.17 and manually edit the openstack pack.

**Comment by nzlosh** [comment]
Closing, python2 support has been dropped from StackStorm.
