### ISSUE TITLE
openstack.network.* issue 

### ISSUE THREAD

**Issue by martypare** [StackStorm-Exchange/stackstorm-openstack#6]
It's most likely something stupid that I am missing but I keep getting the following error when trying to list networks, The rest of the setup appears to be ok since I can list servers(as an example). Any help is appreciated.
```
st2 run openstack.network.list
.
id: 5893f3af49f1e60985f14809
status: failed
parameters: None
result:
exit_code: 1
result: None
stderr: "Traceback (most recent call last):
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 242, in
obj.run()
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 154, in run
output = action.run(**self._parameters)
File "/opt/stackstorm/packs/openstack/actions/src/lib/base.py", line 25, in run
self.parser = self._get_parser(kwargs.pop('ep'))
File "/opt/stackstorm/packs/openstack/actions/src/lib/base.py", line 75, in _get_parser
return command.get_parser('autogen')
File "/opt/stackstorm/st2/lib/python2.7/site-packages/openstackclient/network/common.py", line 146, in get_parser
if self.app.client_manager.is_network_endpoint_enabled():
AttributeError: 'NoneType' object has no attribute 'client_manager'
"
stdout: '
```

**Comment by LindsayHill** [comment]
I don't think it's just you. Will take a look and see if I can figure out what's happening

**Comment by LindsayHill** [comment]
Had a bit of a look around. Looks like there's been a few changes to the Python Openstackclient. Running the autogen.py script results in a few changes to the generated metadata files, although it doesn't seem to resolve all the issues here.

**Comment by humblearner** [comment]
@LindsayHill: `autogen.py` is giving following error: 

```
Unable to generate network.show: 'NoneType' object has no attribute 'client_manager'
Unable to generate network.create: 'NoneType' object has no attribute 'client_manager'
Unable to generate network.delete: 'NoneType' object has no attribute 'client_manager'
Unable to generate network.list: 'NoneType' object has no attribute 'client_manager'
```

**Comment by LindsayHill** [comment]
@humblearner Yeah, looks like the top-level show/create/delete/list options have gone. You can still do `openstack network list` at the CLI, but it seems like they're pushing us towards using things like `network [agent|qos|meter|segment|...] list`?

**Comment by martypare** [comment]
Curious to know how people go arround this.. They use core.remote to where the client is installed and run it natively remotely?

**Comment by LindsayHill** [comment]
@martypare not sure - they may have an install with an older open stack client library where this still worked

**Comment by LindsayHill** [comment]
Now that we have the `neutron` actions available (https://github.com/StackStorm-Exchange/stackstorm-openstack/pull/13), I don't think we need to figure this one out
